# Generated by Django 3.1.6 on 2021-02-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210221_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
