# Generated by Django 3.1.7 on 2021-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210305_0935'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=True), name='check_user'),
        ),
    ]
